name: topi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  permission_handler: ^8.1.0
  image_picker: ^0.8.4+4
  flutter_launcher_icons: ^0.9.0
  expandable: ^5.0.1
  liquid_progress_indicator: ^0.4.0
  cached_network_image: ^3.1.0
  horizontal_card_pager: ^1.1.1
  image_cropper: ^1.4.1
  lottie: ^1.1.0
  share_plus: ^2.1.4
  fluttertoast: ^8.0.8
  path_provider: ^2.0.2
  chewie: ^1.2.2
  video_player: ^2.1.14
  flutter_native_splash: ^1.2.0
  audioplayers: ^0.19.1
  flutter_spinkit: ^5.1.0
  external_path: 1.0.1
  gallery_saver: ^2.3.2
  shared_preferences: ^2.0.12
  font_awesome_flutter: ^9.2.0
  in_app_review: ^2.0.4
  new_version: ^0.2.3
  google_mobile_ads: 0.13.6
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.0
  firebase_core: ^1.4.0
  curved_navigation_bar: ^1.0.1
  better_player: ^0.0.81
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_pdfview: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true


flutter_native_splash:
  color: '#fafafa'
  image: assets/splash.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: FredokaOne
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
